chore: icon header

diff --git a/.github/workflows/fly-deploy.yml b/.github/workflows/fly-deploy.yml
--- a/.github/workflows/fly-deploy.yml
+++ b/.github/workflows/fly-deploy.yml
@@ -2,14 +2,20 @@ name: Fly Deploy
 on:
   push:
     branches: [main]
+
 jobs:
   deploy:
     runs-on: ubuntu-latest
+    # environment: production
+    env:
+      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} # BẮT BUỘC
     steps:
       - uses: actions/checkout@v4
       - uses: superfly/flyctl-actions/setup-flyctl@master
+
+      - name: Check token presence
+        run: 'test -n "$FLY_API_TOKEN" && echo "FLY_API_TOKEN is set" || (echo "missing token" && exit 1)'
+
       - name: Deploy app
-        env:
-          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
-        run: |
-          flyctl deploy --remote-only -c fly.toml
+        run: flyctl deploy --remote-only -c fly.toml
+        working-directory: .
